# Generated by Django 5.1.5 on 2025-03-04 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
