# Generated by Django 5.1.5 on 2025-03-04 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
