# Generated by Django 5.1.5 on 2025-03-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
