# Generated by Django 5.1.5 on 2025-03-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_remove_userprofile_name_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
