# Generated by Django 5.1.5 on 2025-03-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_demolitionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demolitionrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='demolitions/'),
        ),
    ]
