# Generated by Django 5.1.5 on 2025-03-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_sellrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveIntegerField(help_text='Age of the antique in years')),
                ('image', models.ImageField(blank=True, null=True, upload_to='antiques/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
