# Generated by Django 5.1.5 on 2025-03-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0014_antique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antique',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
