# Generated by Django 5.1.5 on 2025-03-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_alter_antique_added_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antique',
            options={'verbose_name_plural': 'Antiques'},
        ),
        migrations.AlterField(
            model_name='antique',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age of the antique in years', null=True),
        ),
    ]
