# Generated by Django 5.1.5 on 2025-04-03 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0026_alter_cartitem_unique_together_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
